{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\compat\\v2_compat.py:61: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "non-resource variables are not supported in the long term\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "tf.compat.v1.disable_eager_execution()\n",
    "tf.compat.v1.disable_v2_behavior()\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "from sklearn import preprocessing as pre\n",
    "import glob\n",
    "from PIL import Image as im\n",
    "import matplotlib.pyplot as plt\n",
    "from pylab import *\n",
    "from Lib import random\n",
    "\n",
    "np.random.seed(0)\n",
    "\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'1.14.0'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "tf.__version__"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class FLAGS():\n",
    "    pass\n",
    "FLAGS.model_dir='\\\\Users\\\\shiely\\\\Projects\\\\main_outrig\\\\ML4LITHO'\n",
    "#FLAGS.model_dir = '\\\\Users\\\\shiely\\\\Projects\\\\main_outrig\\\\auto-encoder-04\\\\context-off-49'\n",
    "FLAGS.data_dir = '\\\\Users\\\\shiely\\\\Projects\\\\main_outrig'\n",
    "FLAGS.model_name = 'context_off_49'\n",
    "FLAGS.batch_size = 128\n",
    "FLAGS.learning_rate = 0.0001\n",
    "FLAGS.l2_reg = 0.05\n",
    "FLAGS.noise_level = 0.00\n",
    "FLAGS.dropout_rate = 0.5\n",
    "FLAGS.resume_training = False\n",
    "FLAGS.max_steps = 1000000\n",
    "FLAGS.eval_steps = 100# Customize for \n",
    "#FLAGS.logdir = '\\\\Users\\\\shiely\\\\Projects\\\\main_outrig\\\\auto-encoder-04\\\\context-off-49'\n",
    "FLAGS.logdir = '\\\\Users\\\\shiely\\\\Projects\\\\main_outrig\\\\logs\\\\ML4LITHO'\n",
    "FLAGS.projectordir = FLAGS.logdir +'projector\\\\'\n",
    "FLAGS.dec_in_channels = 1\n",
    "FLAGS.n_latent = 64\n",
    "FLAGS.image_dim = 48\n",
    "FLAGS.beta=0.05\n",
    "FLAGS.percent_of_train=90\n",
    "FLAGS.sample_size=800\n",
    "FLAGS.training_epochs=10000\n",
    "FLAGS.context_on=False\n",
    "FLAGS.shuffle_data=True\n",
    "LOGDIR=FLAGS.logdir\n",
    "\n",
    "scopes=['NetLayer/LogitsLayer/Logits:0','NetLayer/MetricsLayer/labels:0']\n",
    "summary_writer = tf.compat.v1.summary.FileWriter(FLAGS.logdir)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "loaded masks, designs and contects of shapes (800, 48, 48) (800, 48, 48) (800, 48, 48) and 800 elements.\n",
      "everybodys shuffling : shuf? True perc 90 start_test_index 640 data shape 800\n",
      "shuffled shape (800, 48, 48)\n"
     ]
    }
   ],
   "source": [
    "from design_target_to_mask_problem import mask_design_and_context_data_generation\n",
    "data_sets= mask_design_and_context_data_generation(FLAGS)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# first make it work for VAE (tues)\n",
    "# then make it work for linear, perceptrion, mlp, cnn (weds)\n",
    "# then make it work for gan (thurs)\n",
    "# then put on github (fri)\n",
    "# then write slides (fri-sat-sun)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_input_fn(data,\n",
    "                      mode=tf.estimator.ModeKeys.EVAL,\n",
    "                      batch_size=1): \n",
    "    def input_fn():\n",
    "        if mode == tf.estimator.ModeKeys.EVAL:\n",
    "            masks   = data.test.masks\n",
    "            designs = data.test.designs\n",
    "            contexts= data.test.contexts\n",
    "            print('loading training input : masks {} designs {} contexts {}'.\n",
    "                  format(masks.shape,designs.shape,contexts.shape))\n",
    "            num_epochs = 1\n",
    "        elif mode   == tf.estimator.ModeKeys.TRAIN:\n",
    "            masks   = data.train.masks\n",
    "            designs = data.train.designs\n",
    "            contexts= data.train.contexts\n",
    "            print('loadingeval input : masks {} designs {} contexts {}'.\n",
    "                  format(masks.shape,designs.shape,contexts.shape))\n",
    "            num_epochs=None\n",
    "        else:\n",
    "            assert(False)\n",
    "\n",
    "        is_shuffle = (mode == tf.estimator.ModeKeys.TRAIN)\n",
    "\n",
    "        return tf.compat.v1.estimator.inputs.numpy_input_fn(\n",
    "          batch_size=batch_size,\n",
    "          shuffle=is_shuffle,\n",
    "          x={'masks': masks,'designs': designs, 'contexts':contexts},\n",
    "          y=None,\n",
    "          num_epochs=num_epochs)\n",
    "\n",
    "    return input_fn()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def serving_input_fn():\n",
    "    input_masks= tf.placeholder(shape=[None, FLAGS.image_dim*FLAGS.image_dim], dtype=tf.float32, name='masks')\n",
    "    input_designs = tf.placeholder(shape=[None, FLAGS.image_dim*FLAGS.image_dim], dtype=tf.float32, name='designs')\n",
    "    input_contexts= tf.placeholder(shape=[None, FLAGS.image_dim*FLAGS.image_dim], dtype=tf.float32, name='contexts')\n",
    "\n",
    "    features ={'masks' : input_masks, 'designs' : input_designs, 'contexts': input_contexts}\n",
    "    receiver_tensors = {'masks' : input_masks, 'designs' : input_designs, 'contexts' : input_contexts}\n",
    "    return tf.estimator.export.ServingInputReceiver(features, receiver_tensors)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "from variational_auto_encoder_model import get_bayes_estimator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:tensorflow:Using config: {'_model_dir': '\\\\Users\\\\shiely\\\\Projects\\\\main_outrig\\\\ML4LITHO\\\\context_off_49', '_tf_random_seed': 19851211, '_save_summary_steps': 100, '_save_checkpoints_steps': 1000, '_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true\n",
      "graph_options {\n",
      "  rewrite_options {\n",
      "    meta_optimizer_iterations: ONE\n",
      "  }\n",
      "}\n",
      ", '_keep_checkpoint_max': 2, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x0000024E80603D08>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}\n",
      "loadingeval input : masks (720, 48, 48) designs (720, 48, 48) contexts (720, 48, 48)\n",
      "loadingeval input : masks (720, 48, 48) designs (720, 48, 48) contexts (720, 48, 48)\n",
      "loading training input : masks (160, 48, 48) designs (160, 48, 48) contexts (160, 48, 48)\n",
      "Removing previous artifacts...\n",
      "INFO:tensorflow:Not using Distribute Coordinator.\n",
      "INFO:tensorflow:Running training and evaluation locally (non-distributed).\n",
      "INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps 1000 or save_checkpoints_secs None.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\training\\training_util.py:236: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\inputs\\queues\\feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow_estimator\\python\\estimator\\inputs\\queues\\feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\Projects\\git\\ML4LITHO_2020\\ML4LITHO_2020\\GenerativeModels\\variational_auto_encoder_model.py:7: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.\n",
      "\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\ops\\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024E849BDF78> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024E849BDF78>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024E849BDF78> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024E849BDF78>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(128, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(128, 64), dtype=float32)\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\ops\\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "mean Tensor(\"split_1:0\", shape=(128, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(128, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Create CheckpointSaverHook.\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\training\\monitored_session.py:875: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "To construct input pipelines, use the `tf.data` module.\n",
      "INFO:tensorflow:Saving checkpoints for 0 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:loss = 4792.6143, step = 0\n",
      "INFO:tensorflow:global_step/sec: 6.041\n",
      "INFO:tensorflow:loss = 2156.8113, step = 100 (16.558 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64372\n",
      "INFO:tensorflow:loss = 2092.9006, step = 200 (15.049 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64567\n",
      "INFO:tensorflow:loss = 2090.5254, step = 300 (15.047 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.6445\n",
      "INFO:tensorflow:loss = 1787.0325, step = 400 (15.049 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64551\n",
      "INFO:tensorflow:loss = 1411.615, step = 500 (15.049 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64411\n",
      "INFO:tensorflow:loss = 1186.7915, step = 600 (15.052 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64412\n",
      "INFO:tensorflow:loss = 1084.9755, step = 700 (15.054 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64364\n",
      "INFO:tensorflow:loss = 991.1005, step = 800 (15.048 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64568\n",
      "INFO:tensorflow:loss = 934.06824, step = 900 (15.047 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 1000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024EA81E5E58> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024EA81E5E58>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024EA81E5E58> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024EA81E5E58>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(?, 64), dtype=float32)\n",
      "mean Tensor(\"split_1:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(?, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-01-28T22:17:30Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\training\\saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file APIs to check for files with this prefix.\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-1000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [10/100]\n",
      "INFO:tensorflow:Evaluation [20/100]\n",
      "INFO:tensorflow:Evaluation [30/100]\n",
      "INFO:tensorflow:Evaluation [40/100]\n",
      "INFO:tensorflow:Evaluation [50/100]\n",
      "INFO:tensorflow:Evaluation [60/100]\n",
      "INFO:tensorflow:Evaluation [70/100]\n",
      "INFO:tensorflow:Evaluation [80/100]\n",
      "INFO:tensorflow:Evaluation [90/100]\n",
      "INFO:tensorflow:Evaluation [100/100]\n",
      "INFO:tensorflow:Finished evaluation at 2020-01-28-22:17:36\n",
      "INFO:tensorflow:Saving dict for global step 1000: global_step = 1000, loss = 909.9024, rmse_context = 1.2117378e-08, rmse_design = 0.3407368, rmse_mask = 0.5425018\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 1000: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-1000\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\saved_model\\signature_def_utils_impl.py:201: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-1000\n",
      "INFO:tensorflow:Assets added to graph.\n",
      "INFO:tensorflow:No assets to write.\n",
      "INFO:tensorflow:SavedModel written to: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\export\\Servo\\temp-b'1580278662'\\saved_model.pb\n",
      "INFO:tensorflow:global_step/sec: 2.29445\n",
      "INFO:tensorflow:loss = 904.95233, step = 1000 (43.583 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64024\n",
      "INFO:tensorflow:loss = 876.78015, step = 1100 (15.060 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.64277\n",
      "INFO:tensorflow:loss = 841.1847, step = 1200 (15.053 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.60085\n",
      "INFO:tensorflow:loss = 836.1688, step = 1300 (15.151 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.61853\n",
      "INFO:tensorflow:loss = 789.2497, step = 1400 (15.113 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.48751\n",
      "INFO:tensorflow:loss = 798.5947, step = 1500 (15.409 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.4016\n",
      "INFO:tensorflow:loss = 784.5746, step = 1600 (15.622 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38937\n",
      "INFO:tensorflow:loss = 770.30646, step = 1700 (15.651 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.37752\n",
      "INFO:tensorflow:loss = 743.0287, step = 1800 (15.680 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.33066\n",
      "INFO:tensorflow:loss = 743.9978, step = 1900 (15.795 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 2000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "WARNING:tensorflow:From C:\\Users\\shiely\\AppData\\Local\\Continuum\\anaconda3\\envs\\t2t\\lib\\site-packages\\tensorflow\\python\\training\\saver.py:960: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use standard file APIs to delete files with this prefix.\n",
      "INFO:tensorflow:Skip the current checkpoint eval due to throttle secs (300 secs).\n",
      "INFO:tensorflow:global_step/sec: 4.54836\n",
      "INFO:tensorflow:loss = 732.53076, step = 2000 (21.987 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.47815\n",
      "INFO:tensorflow:loss = 720.95844, step = 2100 (15.437 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46193\n",
      "INFO:tensorflow:loss = 731.56384, step = 2200 (15.484 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.3985\n",
      "INFO:tensorflow:loss = 716.9018, step = 2300 (15.618 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38391\n",
      "INFO:tensorflow:loss = 714.5323, step = 2400 (15.665 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.36599\n",
      "INFO:tensorflow:loss = 701.75354, step = 2500 (15.708 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.21521\n",
      "INFO:tensorflow:loss = 699.7684, step = 2600 (16.091 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.03516\n",
      "INFO:tensorflow:loss = 700.68884, step = 2700 (16.569 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.04949\n",
      "INFO:tensorflow:loss = 689.7116, step = 2800 (16.532 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.03658\n",
      "INFO:tensorflow:loss = 693.1398, step = 2900 (16.564 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 3000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FEB5695E8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FEB5695E8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FEB5695E8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FEB5695E8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(?, 64), dtype=float32)\n",
      "mean Tensor(\"split_1:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(?, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-01-28T22:23:20Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-3000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [10/100]\n",
      "INFO:tensorflow:Evaluation [20/100]\n",
      "INFO:tensorflow:Evaluation [30/100]\n",
      "INFO:tensorflow:Evaluation [40/100]\n",
      "INFO:tensorflow:Evaluation [50/100]\n",
      "INFO:tensorflow:Evaluation [60/100]\n",
      "INFO:tensorflow:Evaluation [70/100]\n",
      "INFO:tensorflow:Evaluation [80/100]\n",
      "INFO:tensorflow:Evaluation [90/100]\n",
      "INFO:tensorflow:Evaluation [100/100]\n",
      "INFO:tensorflow:Finished evaluation at 2020-01-28-22:23:26\n",
      "INFO:tensorflow:Saving dict for global step 3000: global_step = 3000, loss = 711.8886, rmse_context = 2.2386208e-10, rmse_design = 0.3488833, rmse_mask = 0.5660391\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 3000: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-3000\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-3000\n",
      "INFO:tensorflow:Assets added to graph.\n",
      "INFO:tensorflow:No assets to write.\n",
      "INFO:tensorflow:SavedModel written to: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\export\\Servo\\temp-b'1580279006'\\saved_model.pb\n",
      "INFO:tensorflow:global_step/sec: 2.51319\n",
      "INFO:tensorflow:loss = 662.68677, step = 3000 (39.792 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.51832\n",
      "INFO:tensorflow:loss = 686.7033, step = 3100 (15.340 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.37529\n",
      "INFO:tensorflow:loss = 670.2017, step = 3200 (15.685 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.24854\n",
      "INFO:tensorflow:loss = 679.289, step = 3300 (16.003 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.18165\n",
      "INFO:tensorflow:loss = 655.0571, step = 3400 (16.178 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.18678\n",
      "INFO:tensorflow:loss = 671.87744, step = 3500 (16.162 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.17324\n",
      "INFO:tensorflow:loss = 650.8058, step = 3600 (16.201 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.1789\n",
      "INFO:tensorflow:loss = 663.3521, step = 3700 (16.186 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.19425\n",
      "INFO:tensorflow:loss = 656.2866, step = 3800 (16.141 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.1956\n",
      "INFO:tensorflow:loss = 653.6323, step = 3900 (16.140 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 4000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Skip the current checkpoint eval due to throttle secs (300 secs).\n",
      "INFO:tensorflow:global_step/sec: 4.62204\n",
      "INFO:tensorflow:loss = 652.542, step = 4000 (21.635 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.54483\n",
      "INFO:tensorflow:loss = 656.0446, step = 4100 (15.280 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.40754\n",
      "INFO:tensorflow:loss = 655.8894, step = 4200 (15.607 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.20376\n",
      "INFO:tensorflow:loss = 630.7648, step = 4300 (16.118 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.17454\n",
      "INFO:tensorflow:loss = 652.90436, step = 4400 (16.198 sec)\n",
      "INFO:tensorflow:global_step/sec: 5.76841\n",
      "INFO:tensorflow:loss = 634.88257, step = 4500 (17.342 sec)\n",
      "INFO:tensorflow:global_step/sec: 5.09144\n",
      "INFO:tensorflow:loss = 636.61914, step = 4600 (19.641 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.07525\n",
      "INFO:tensorflow:loss = 649.55676, step = 4700 (16.460 sec)\n",
      "INFO:tensorflow:global_step/sec: 5.81135\n",
      "INFO:tensorflow:loss = 647.43396, step = 4800 (17.208 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.0003\n",
      "INFO:tensorflow:loss = 641.3853, step = 4900 (16.664 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 5000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FF71CFCA8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FF71CFCA8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FF71CFCA8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FF71CFCA8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(?, 64), dtype=float32)\n",
      "mean Tensor(\"split_1:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(?, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-01-28T22:29:30Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-5000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [10/100]\n",
      "INFO:tensorflow:Evaluation [20/100]\n",
      "INFO:tensorflow:Evaluation [30/100]\n",
      "INFO:tensorflow:Evaluation [40/100]\n",
      "INFO:tensorflow:Evaluation [50/100]\n",
      "INFO:tensorflow:Evaluation [60/100]\n",
      "INFO:tensorflow:Evaluation [70/100]\n",
      "INFO:tensorflow:Evaluation [80/100]\n",
      "INFO:tensorflow:Evaluation [90/100]\n",
      "INFO:tensorflow:Evaluation [100/100]\n",
      "INFO:tensorflow:Finished evaluation at 2020-01-28-22:29:44\n",
      "INFO:tensorflow:Saving dict for global step 5000: global_step = 5000, loss = 679.53357, rmse_context = 6.5889565e-09, rmse_design = 0.350785, rmse_mask = 0.56935674\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5000: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-5000\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-5000\n",
      "INFO:tensorflow:Assets added to graph.\n",
      "INFO:tensorflow:No assets to write.\n",
      "INFO:tensorflow:SavedModel written to: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\export\\Servo\\temp-b'1580279384'\\saved_model.pb\n",
      "INFO:tensorflow:global_step/sec: 1.56808\n",
      "INFO:tensorflow:loss = 642.3354, step = 5000 (63.770 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.37297\n",
      "INFO:tensorflow:loss = 629.7751, step = 5100 (15.693 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38904\n",
      "INFO:tensorflow:loss = 631.93866, step = 5200 (15.648 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38174\n",
      "INFO:tensorflow:loss = 627.832, step = 5300 (15.675 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.3598\n",
      "INFO:tensorflow:loss = 643.0857, step = 5400 (15.722 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.31412\n",
      "INFO:tensorflow:loss = 626.17285, step = 5500 (15.837 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.49046\n",
      "INFO:tensorflow:loss = 631.62427, step = 5600 (15.405 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.50026\n",
      "INFO:tensorflow:loss = 620.6874, step = 5700 (15.383 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38267\n",
      "INFO:tensorflow:loss = 635.1341, step = 5800 (15.671 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.40441\n",
      "INFO:tensorflow:loss = 622.4365, step = 5900 (15.611 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 6000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Skip the current checkpoint eval due to throttle secs (300 secs).\n",
      "INFO:tensorflow:global_step/sec: 4.32009\n",
      "INFO:tensorflow:loss = 614.174, step = 6000 (23.147 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.54948\n",
      "INFO:tensorflow:loss = 624.3051, step = 6100 (15.268 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46083\n",
      "INFO:tensorflow:loss = 617.0752, step = 6200 (15.480 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.52607\n",
      "INFO:tensorflow:loss = 624.326, step = 6300 (15.321 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.5316\n",
      "INFO:tensorflow:loss = 618.8611, step = 6400 (15.310 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.48071\n",
      "INFO:tensorflow:loss = 621.34375, step = 6500 (15.430 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46459\n",
      "INFO:tensorflow:loss = 622.8858, step = 6600 (15.479 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.35449\n",
      "INFO:tensorflow:loss = 621.7208, step = 6700 (15.731 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46121\n",
      "INFO:tensorflow:loss = 616.011, step = 6800 (15.474 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.43968\n",
      "INFO:tensorflow:loss = 608.8427, step = 6900 (15.529 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 7000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FFE2353A8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FFE2353A8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FFE2353A8> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000024FFE2353A8>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(?, 64), dtype=float32)\n",
      "mean Tensor(\"split_1:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(?, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-01-28T22:35:24Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-7000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [10/100]\n",
      "INFO:tensorflow:Evaluation [20/100]\n",
      "INFO:tensorflow:Evaluation [30/100]\n",
      "INFO:tensorflow:Evaluation [40/100]\n",
      "INFO:tensorflow:Evaluation [50/100]\n",
      "INFO:tensorflow:Evaluation [60/100]\n",
      "INFO:tensorflow:Evaluation [70/100]\n",
      "INFO:tensorflow:Evaluation [80/100]\n",
      "INFO:tensorflow:Evaluation [90/100]\n",
      "INFO:tensorflow:Evaluation [100/100]\n",
      "INFO:tensorflow:Finished evaluation at 2020-01-28-22:35:32\n",
      "INFO:tensorflow:Saving dict for global step 7000: global_step = 7000, loss = 663.17096, rmse_context = 1.2039013e-07, rmse_design = 0.35213047, rmse_mask = 0.5696203\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 7000: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-7000\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-7000\n",
      "INFO:tensorflow:Assets added to graph.\n",
      "INFO:tensorflow:No assets to write.\n",
      "INFO:tensorflow:SavedModel written to: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\export\\Servo\\temp-b'1580279732'\\saved_model.pb\n",
      "INFO:tensorflow:global_step/sec: 2.31523\n",
      "INFO:tensorflow:loss = 622.4794, step = 7000 (43.190 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.52267\n",
      "INFO:tensorflow:loss = 618.9917, step = 7100 (15.333 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.52719\n",
      "INFO:tensorflow:loss = 605.48065, step = 7200 (15.323 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.54883\n",
      "INFO:tensorflow:loss = 612.9134, step = 7300 (15.267 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.56154\n",
      "INFO:tensorflow:loss = 615.34894, step = 7400 (15.241 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.564\n",
      "INFO:tensorflow:loss = 606.09186, step = 7500 (15.234 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.54267\n",
      "INFO:tensorflow:loss = 618.5969, step = 7600 (15.284 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.53915\n",
      "INFO:tensorflow:loss = 611.1234, step = 7700 (15.293 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.52424\n",
      "INFO:tensorflow:loss = 609.8109, step = 7800 (15.332 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.38741\n",
      "INFO:tensorflow:loss = 605.13055, step = 7900 (15.653 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 8000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Skip the current checkpoint eval due to throttle secs (300 secs).\n",
      "INFO:tensorflow:global_step/sec: 3.99318\n",
      "INFO:tensorflow:loss = 602.0573, step = 8000 (25.042 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.40285\n",
      "INFO:tensorflow:loss = 606.2596, step = 8100 (15.618 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.50666\n",
      "INFO:tensorflow:loss = 605.1487, step = 8200 (15.375 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.4866\n",
      "INFO:tensorflow:loss = 602.6976, step = 8300 (15.409 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46328\n",
      "INFO:tensorflow:loss = 607.16003, step = 8400 (15.473 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.42307\n",
      "INFO:tensorflow:loss = 608.8868, step = 8500 (15.568 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.42205\n",
      "INFO:tensorflow:loss = 596.90076, step = 8600 (15.572 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.40125\n",
      "INFO:tensorflow:loss = 604.60364, step = 8700 (15.624 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.43968\n",
      "INFO:tensorflow:loss = 598.589, step = 8800 (15.530 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.44182\n",
      "INFO:tensorflow:loss = 604.73157, step = 8900 (15.520 sec)\n",
      "INFO:tensorflow:Saving checkpoints for 9000 into \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt.\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "WARNING:tensorflow:Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000025004EF4A68> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000025004EF4A68>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000025004EF4A68> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <function get_bayes_estimator.<locals>._model_fn.<locals>.compute_loss at 0x0000025004EF4A68>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "mean Tensor(\"split:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split:1\", shape=(?, 64), dtype=float32)\n",
      "mean Tensor(\"split_1:0\", shape=(?, 64), dtype=float32) logvar Tensor(\"split_1:1\", shape=(?, 64), dtype=float32)\n",
      "(128, 48, 48, 1) (128, 48, 48, 1)\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Starting evaluation at 2020-01-28T22:41:15Z\n",
      "INFO:tensorflow:Graph was finalized.\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-9000\n",
      "INFO:tensorflow:Running local_init_op.\n",
      "INFO:tensorflow:Done running local_init_op.\n",
      "INFO:tensorflow:Evaluation [10/100]\n",
      "INFO:tensorflow:Evaluation [20/100]\n",
      "INFO:tensorflow:Evaluation [30/100]\n",
      "INFO:tensorflow:Evaluation [40/100]\n",
      "INFO:tensorflow:Evaluation [50/100]\n",
      "INFO:tensorflow:Evaluation [60/100]\n",
      "INFO:tensorflow:Evaluation [70/100]\n",
      "INFO:tensorflow:Evaluation [80/100]\n",
      "INFO:tensorflow:Evaluation [90/100]\n",
      "INFO:tensorflow:Evaluation [100/100]\n",
      "INFO:tensorflow:Finished evaluation at 2020-01-28-22:41:23\n",
      "INFO:tensorflow:Saving dict for global step 9000: global_step = 9000, loss = 651.57166, rmse_context = 7.7877706e-07, rmse_design = 0.35112008, rmse_mask = 0.5695136\n",
      "INFO:tensorflow:Saving 'checkpoint_path' summary for global step 9000: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-9000\n",
      "INFO:tensorflow:Calling model_fn.\n",
      "hparams\n",
      "image_dim 48\n",
      "INFO:tensorflow:Done calling model_fn.\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Classify: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Regress: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict', 'serving_default']\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Train: None\n",
      "INFO:tensorflow:Signatures INCLUDED in export for Eval: None\n",
      "INFO:tensorflow:Restoring parameters from \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\model.ckpt-9000\n",
      "INFO:tensorflow:Assets added to graph.\n",
      "INFO:tensorflow:No assets to write.\n",
      "INFO:tensorflow:SavedModel written to: \\Users\\shiely\\Projects\\main_outrig\\ML4LITHO\\context_off_49\\export\\Servo\\temp-b'1580280083'\\saved_model.pb\n",
      "INFO:tensorflow:global_step/sec: 2.07861\n",
      "INFO:tensorflow:loss = 601.63666, step = 9000 (48.110 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.14872\n",
      "INFO:tensorflow:loss = 602.5, step = 9100 (16.265 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.25065\n",
      "INFO:tensorflow:loss = 595.97864, step = 9200 (15.995 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.40626\n",
      "INFO:tensorflow:loss = 594.51605, step = 9300 (15.615 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.39215\n",
      "INFO:tensorflow:loss = 594.4331, step = 9400 (15.641 sec)\n",
      "INFO:tensorflow:global_step/sec: 6.46857\n",
      "INFO:tensorflow:loss = 589.1735, step = 9500 (15.458 sec)\n"
     ]
    }
   ],
   "source": [
    "import os as os\n",
    "run_config = tf.estimator.RunConfig(\n",
    "    model_dir=os.path.join(FLAGS.model_dir, FLAGS.model_name),\n",
    "    save_checkpoints_steps=1000,\n",
    "    keep_checkpoint_max=2,\n",
    "    tf_random_seed=19851211\n",
    ")\n",
    "\n",
    "#from tensorboard.plugins.hparams import api as hp\n",
    "\n",
    "hparams = {\n",
    "    \"batch_size\" : FLAGS.batch_size,\n",
    "    \"encoder_hidden_units\" : FLAGS.n_latent,\n",
    "    \"learning_rate\"  :FLAGS.learning_rate,\n",
    "    \"l2_reg\" : FLAGS.l2_reg,\n",
    "    \"noise_level\" : FLAGS.noise_level,\n",
    "    \"dropout_rate\" : FLAGS.dropout_rate,\n",
    "    \"image_dim\": FLAGS.image_dim,\n",
    "    \"n_latent\":FLAGS.n_latent,\n",
    "    \"context_on\":FLAGS.context_on,\n",
    "    \"beta\":FLAGS.beta\n",
    "}\n",
    "\n",
    "estimator = get_bayes_estimator(run_config, hparams)\n",
    "\n",
    "train_spec = tf.estimator.TrainSpec(\n",
    "    input_fn=generate_input_fn(data_sets,\n",
    "                             mode=tf.estimator.ModeKeys.TRAIN,\n",
    "                             batch_size=FLAGS.batch_size),\n",
    "    max_steps=FLAGS.max_steps, hooks=None)\n",
    "train_input_fn=generate_input_fn(data_sets,\n",
    "                             mode=tf.estimator.ModeKeys.TRAIN,\n",
    "                             batch_size=FLAGS.batch_size)\n",
    "\n",
    "exporter = tf.estimator.LatestExporter(\n",
    "      name='Servo',\n",
    "      serving_input_receiver_fn=serving_input_fn,\n",
    "      exports_to_keep=5)\n",
    "\n",
    "eval_spec = tf.estimator.EvalSpec(\n",
    "    input_fn=generate_input_fn(data_sets),\n",
    "    steps=FLAGS.eval_steps, exporters=exporter, throttle_secs=300)\n",
    "import shutil\n",
    "if not FLAGS.resume_training:\n",
    "    print('Removing previous artifacts...')\n",
    "    shutil.rmtree(os.path.join(FLAGS.model_dir, FLAGS.model_name), ignore_errors=True)\n",
    "\n",
    "#estimator.train(train_input_fn)\n",
    "tf.compat.v1.estimator.train_and_evaluate(estimator, train_spec, eval_spec)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "estimator.export_saved_model('saved_model',serving_input_fn)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_sets.test.masks.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "export_dir =os.path.join(FLAGS.model_dir, FLAGS.model_name, 'export\\\\Servo\\\\')\n",
    "saved_model_dir = '\\\\Users\\\\shiely\\\\saved_model\\\\1572404268'\n",
    "\n",
    "predictor_fn = tf.contrib.predictor.from_saved_model(\n",
    "  export_dir = saved_model_dir,\n",
    "  signature_def_key='predict')\n",
    "\n",
    "output = predictor_fn({'masks': np.reshape(data_sets.train.masks[:100],[-1,FLAGS.image_dim*FLAGS.image_dim]),\n",
    "                      'designs': np.reshape(data_sets.train.designs[:100],[-1,FLAGS.image_dim*FLAGS.image_dim]),\n",
    "                      'contexts': np.reshape(data_sets.train.contexts[:100],[-1,FLAGS.image_dim*FLAGS.image_dim])})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "x = 19\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(10,4))\n",
    "ax1.set_title('original mask')\n",
    "ax1.imshow(data_sets.train.masks[x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "\n",
    "ax2.set_title('reconstructed mask')\n",
    "ax2.imshow(output['mask_reconstruction'][x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "plt.show()\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(10,4))\n",
    "\n",
    "ax1.set_title('original design')\n",
    "ax1.imshow(data_sets.train.designs[x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "\n",
    "ax2.set_title('reconstructed design')\n",
    "ax2.imshow(output['design_reconstruction'][x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "\n",
    "plt.show()\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(10,4))\n",
    "\n",
    "ax1.set_title('original context')\n",
    "ax1.imshow(data_sets.train.contexts[x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "\n",
    "ax2.set_title('reconstructed context')\n",
    "ax2.imshow(output['context_reconstruction'][x].reshape(FLAGS.image_dim,FLAGS.image_dim))\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
